// Generated by scripts/build-verses-of-the-day.py — do not edit by hand.
// Source: ACTS Prayers.xlsx (350 verses)

export interface DailyVerse {
  number: string;
  reference: string;
  text: string;
}

export const VERSES_OF_THE_DAY: DailyVerse[] = [
  {
    number: "001",
    reference: "Psalm 95:6",
    text: "Come, let us bow down in worship, let us kneel before the Lord our Maker.",
  },
  {
    number: "002",
    reference: "Isaiah 6:3",
    text: "Holy, holy, holy is the Lord Almighty; the whole earth is full of his glory.",
  },
  {
    number: "003",
    reference: "Psalm 103:1",
    text: "Praise the Lord, my soul; all my inmost being, praise his holy name.",
  },
  {
    number: "004",
    reference: "Revelation 4:11",
    text: "You are worthy, our Lord and God, to receive glory and honor and power.",
  },
  {
    number: "005",
    reference: "Psalm 145:3",
    text: "Great is the Lord and most worthy of praise; his greatness no one can fathom.",
  },
  {
    number: "006",
    reference: "1 Chronicles 29:11",
    text: "Yours, Lord, is the greatness and the power and the glory and the majesty.",
  },
  {
    number: "007",
    reference: "Psalm 96:9",
    text: "Worship the Lord in the splendor of his holiness; tremble before him.",
  },
  {
    number: "008",
    reference: "Exodus 15:11",
    text: "Who among the gods is like you, Lord? Majestic in holiness.",
  },
  {
    number: "009",
    reference: "Psalm 18:2",
    text: "The Lord is my rock, my fortress and my deliverer.",
  },
  {
    number: "010",
    reference: "Deuteronomy 6:5",
    text: "Love the Lord your God with all your heart and with all your soul.",
  },
  {
    number: "011",
    reference: "Psalm 46:1",
    text: "God is our refuge and strength, an ever-present help in trouble.",
  },
  {
    number: "012",
    reference: "Psalm 27:1",
    text: "The Lord is my light and my salvation, whom shall I fear?",
  },
  {
    number: "013",
    reference: "Psalm 119:105",
    text: "Your word is a lamp for my feet, a light on my path.",
  },
  {
    number: "014",
    reference: "Proverbs 3:5–6",
    text: "Trust in the Lord with all your heart and lean not on your own understanding.",
  },
  {
    number: "015",
    reference: "Psalm 37:4",
    text: "Take delight in the Lord, and he will give you the desires of your heart.",
  },
  {
    number: "016",
    reference: "Matthew 6:33",
    text: "Seek first his kingdom and his righteousness.",
  },
  {
    number: "017",
    reference: "Psalm 23:1",
    text: "The Lord is my shepherd; I lack nothing.",
  },
  {
    number: "018",
    reference: "John 10:11",
    text: "I am the good shepherd. The good shepherd lays down his life.",
  },
  {
    number: "019",
    reference: "Romans 8:1",
    text: "There is now no condemnation for those who are in Christ Jesus.",
  },
  {
    number: "020",
    reference: "2 Corinthians 5:17",
    text: "If anyone is in Christ, the new creation has come.",
  },
  {
    number: "021",
    reference: "Galatians 2:20",
    text: "I have been crucified with Christ and I no longer live.",
  },
  {
    number: "022",
    reference: "Ephesians 2:8",
    text: "For it is by grace you have been saved, through faith.",
  },
  {
    number: "023",
    reference: "Colossians 1:16",
    text: "All things have been created through him and for him.",
  },
  {
    number: "024",
    reference: "Hebrews 4:16",
    text: "Let us then approach God’s throne of grace with confidence.",
  },
  {
    number: "025",
    reference: "James 1:5",
    text: "If any of you lacks wisdom, you should ask God.",
  },
  {
    number: "026",
    reference: "Psalm 51:10",
    text: "Create in me a pure heart, O God.",
  },
  {
    number: "027",
    reference: "Micah 6:8",
    text: "Act justly, love mercy, and walk humbly with your God.",
  },
  {
    number: "028",
    reference: "Matthew 5:16",
    text: "Let your light shine before others.",
  },
  {
    number: "029",
    reference: "John 15:5",
    text: "Apart from me you can do nothing.",
  },
  {
    number: "030",
    reference: "Romans 12:1",
    text: "Offer your bodies as a living sacrifice.",
  },
  {
    number: "031",
    reference: "Psalm 34:8",
    text: "Taste and see that the Lord is good; blessed is the one who takes refuge in him.",
  },
  {
    number: "032",
    reference: "Psalm 121:1–2",
    text: "My help comes from the Lord, the Maker of heaven and earth.",
  },
  {
    number: "033",
    reference: "Isaiah 40:31",
    text: "Those who hope in the Lord will renew their strength.",
  },
  {
    number: "034",
    reference: "Lamentations 3:22–23",
    text: "Because of the Lord’s great love we are not consumed.",
  },
  {
    number: "035",
    reference: "Matthew 11:28",
    text: "Come to me, all you who are weary and burdened.",
  },
  {
    number: "036",
    reference: "John 14:6",
    text: "I am the way and the truth and the life.",
  },
  {
    number: "037",
    reference: "Romans 5:8",
    text: "While we were still sinners, Christ died for us.",
  },
  {
    number: "038",
    reference: "1 Corinthians 10:13",
    text: "God is faithful; he will not let you be tempted beyond what you can bear.",
  },
  {
    number: "039",
    reference: "2 Corinthians 12:9",
    text: "My grace is sufficient for you.",
  },
  {
    number: "040",
    reference: "Galatians 5:22–23",
    text: "The fruit of the Spirit is love, joy, peace…",
  },
  {
    number: "041",
    reference: "Ephesians 6:10",
    text: "Be strong in the Lord and in his mighty power.",
  },
  {
    number: "042",
    reference: "Philippians 1:6",
    text: "He who began a good work in you will carry it on.",
  },
  {
    number: "043",
    reference: "Philippians 4:13",
    text: "I can do all this through him who gives me strength.",
  },
  {
    number: "044",
    reference: "Colossians 3:17",
    text: "Whatever you do… do it all in the name of the Lord Jesus.",
  },
  {
    number: "045",
    reference: "1 Thessalonians 5:16–18",
    text: "Rejoice always, pray continually, give thanks.",
  },
  {
    number: "046",
    reference: "2 Timothy 1:7",
    text: "God gave us a spirit not of fear but of power.",
  },
  {
    number: "047",
    reference: "Hebrews 12:11",
    text: "No discipline seems pleasant at the time.",
  },
  {
    number: "048",
    reference: "James 4:8",
    text: "Come near to God and he will come near to you.",
  },
  {
    number: "049",
    reference: "1 Peter 5:7",
    text: "Cast all your anxiety on him because he cares for you.",
  },
  {
    number: "050",
    reference: "1 John 1:7",
    text: "The blood of Jesus purifies us from all sin.",
  },
  {
    number: "051",
    reference: "Psalm 19:14",
    text: "May the words of my mouth and the meditation of my heart be pleasing in your sight, Lord.",
  },
  {
    number: "052",
    reference: "Psalm 37:5",
    text: "Commit your way to the Lord; trust in him and he will do this.",
  },
  {
    number: "053",
    reference: "Psalm 118:24",
    text: "This is the day the Lord has made; let us rejoice and be glad in it.",
  },
  {
    number: "054",
    reference: "Isaiah 41:10",
    text: "So do not fear, for I am with you; do not be dismayed, for I am your God.",
  },
  {
    number: "055",
    reference: "Jeremiah 29:11",
    text: "For I know the plans I have for you,” declares the Lord.",
  },
  {
    number: "056",
    reference: "Matthew 28:20",
    text: "I am with you always, to the very end of the age.",
  },
  {
    number: "057",
    reference: "John 3:16",
    text: "For God so loved the world that he gave his one and only Son.",
  },
  {
    number: "058",
    reference: "John 15:12",
    text: "My command is this: Love each other as I have loved you.",
  },
  {
    number: "059",
    reference: "Romans 8:28",
    text: "And we know that in all things God works for the good of those who love him.",
  },
  {
    number: "060",
    reference: "Romans 12:2",
    text: "Do not conform to the pattern of this world, but be transformed by the renewing of your mind.",
  },
  {
    number: "061",
    reference: "1 Corinthians 16:13",
    text: "Be on your guard; stand firm in the faith; be courageous; be strong.",
  },
  {
    number: "062",
    reference: "2 Corinthians 5:21",
    text: "God made him who had no sin to be sin for us.",
  },
  {
    number: "063",
    reference: "Galatians 6:9",
    text: "Let us not become weary in doing good, for at the proper time we will reap a harvest.",
  },
  {
    number: "064",
    reference: "Ephesians 3:16–17",
    text: "I pray that out of his glorious riches he may strengthen you with power through his Spirit.",
  },
  {
    number: "065",
    reference: "Philippians 4:19",
    text: "And my God will meet all your needs according to the riches of his glory in Christ Jesus.",
  },
  {
    number: "066",
    reference: "Colossians 3:16",
    text: "Let the message of Christ dwell among you richly as you teach and admonish one another.",
  },
  {
    number: "067",
    reference: "1 Thessalonians 5:11",
    text: "Encourage one another and build each other up.",
  },
  {
    number: "068",
    reference: "2 Timothy 3:16",
    text: "All Scripture is God-breathed and is useful for teaching, rebuking, correcting, and training in righteousness.",
  },
  {
    number: "069",
    reference: "Hebrews 13:8",
    text: "Jesus Christ is the same yesterday and today and forever.",
  },
  {
    number: "070",
    reference: "1 John 4:19",
    text: "We love because he first loved us.",
  },
  {
    number: "071",
    reference: "Revelation 3:20",
    text: "Here I am! I stand at the door and knock.",
  },
  {
    number: "072",
    reference: "Psalm 63:1",
    text: "You, God, are my God, earnestly I seek you; I thirst for you.",
  },
  {
    number: "073",
    reference: "Psalm 91:1–2",
    text: "Whoever dwells in the shelter of the Most High will rest in the shadow of the Almighty.",
  },
  {
    number: "074",
    reference: "Isaiah 26:3",
    text: "You will keep in perfect peace those whose minds are steadfast.",
  },
  {
    number: "075",
    reference: "Jeremiah 33:3",
    text: "Call to me and I will answer you and tell you great and unsearchable things.",
  },
  {
    number: "076",
    reference: "Matthew 5:9",
    text: "Blessed are the peacemakers, for they will be called children of God.",
  },
  {
    number: "077",
    reference: "Matthew 6:14–15",
    text: "For if you forgive other people when they sin against you, your heavenly Father will also forgive you.",
  },
  {
    number: "078",
    reference: "Luke 11:9",
    text: "Ask and it will be given to you; seek and you will find.",
  },
  {
    number: "079",
    reference: "John 8:12",
    text: "I am the light of the world. Whoever follows me will never walk in darkness.",
  },
  {
    number: "080",
    reference: "Acts 1:8",
    text: "You will receive power when the Holy Spirit comes on you; and you will be my witnesses.",
  },
  {
    number: "081",
    reference: "Romans 15:13",
    text: "May the God of hope fill you with all joy and peace as you trust in him, so that you may overflow with hope.",
  },
  {
    number: "082",
    reference: "1 Peter 2:9",
    text: "But you are a chosen people, a royal priesthood, a holy nation.",
  },
  {
    number: "083",
    reference: "1 John 5:14",
    text: "This is the confidence we have in approaching God: that if we ask anything according to his will, he hears us.",
  },
  {
    number: "084",
    reference: "Psalm 121:7–8",
    text: "The Lord will keep you from all harm, he will watch over your life; the Lord will watch over your coming and going both now and forevermore.",
  },
  {
    number: "085",
    reference: "Isaiah 43:2",
    text: "When you pass through the waters, I will be with you; and when you pass through rivers, they will not sweep over you.",
  },
  {
    number: "086",
    reference: "Jeremiah 1:5",
    text: "Before I formed you in the womb I knew you, before you were born I set you apart.",
  },
  {
    number: "087",
    reference: "Matthew 7:7",
    text: "Ask and it will be given to you; seek and you will find; knock and the door will be opened to you.",
  },
  {
    number: "088",
    reference: "Matthew 22:37",
    text: "Love the Lord your God with all your heart and with all your soul and with all your mind.",
  },
  {
    number: "089",
    reference: "John 14:27",
    text: "Peace I leave with you; my peace I give you.",
  },
  {
    number: "090",
    reference: "John 16:33",
    text: "In this world you will have trouble. But take heart! I have overcome the world.",
  },
  {
    number: "091",
    reference: "Romans 8:31",
    text: "If God is for us, who can be against us?",
  },
  {
    number: "092",
    reference: "Romans 12:12",
    text: "Be joyful in hope, patient in affliction, faithful in prayer.",
  },
  {
    number: "093",
    reference: "1 Corinthians 15:58",
    text: "Give yourselves fully to the work of the Lord, because you know that your labor in the Lord is not in vain.",
  },
  {
    number: "094",
    reference: "Galatians 2:20",
    text: "I have been crucified with Christ and I no longer live, but Christ lives in me.",
  },
  {
    number: "095",
    reference: "Galatians 5:16",
    text: "Walk by the Spirit, and you will not gratify the desires of the flesh.",
  },
  {
    number: "096",
    reference: "Ephesians 4:32",
    text: "Be kind and compassionate to one another, forgiving each other, just as in Christ God forgave you.",
  },
  {
    number: "097",
    reference: "Ephesians 5:18",
    text: "Be filled with the Spirit, speaking to one another with psalms, hymns, and songs from the Spirit.",
  },
  {
    number: "098",
    reference: "Philippians 4:6",
    text: "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God.",
  },
  {
    number: "099",
    reference: "Philippians 4:7",
    text: "And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.",
  },
  {
    number: "100",
    reference: "Colossians 3:12–13",
    text: "Clothe yourselves with compassion, kindness, humility, gentleness and patience. Bear with each other and forgive one another.",
  },
  {
    number: "101",
    reference: "1 Thessalonians 5:16–18",
    text: "Rejoice always, pray continually, give thanks in all circumstances.",
  },
  {
    number: "102",
    reference: "2 Timothy 3:16–17",
    text: "All Scripture is God-breathed and is useful for teaching, rebuking, correcting, and training in righteousness.",
  },
  {
    number: "103",
    reference: "Hebrews 4:12",
    text: "For the word of God is alive and active. Sharper than any double-edged sword.",
  },
  {
    number: "104",
    reference: "Hebrews 11:1",
    text: "Now faith is confidence in what we hope for and assurance about what we do not see.",
  },
  {
    number: "105",
    reference: "James 1:2–3",
    text: "Consider it pure joy, my brothers and sisters, whenever you face trials, because you know that the testing of your faith produces perseverance.",
  },
  {
    number: "106",
    reference: "James 1:5",
    text: "If any of you lacks wisdom, you should ask God.",
  },
  {
    number: "107",
    reference: "1 Peter 1:15–16",
    text: "Be holy, because I am holy.",
  },
  {
    number: "108",
    reference: "1 Peter 5:6–7",
    text: "Humble yourselves, therefore, under God’s mighty hand, that he may lift you up.",
  },
  {
    number: "109",
    reference: "1 John 1:9",
    text: "If we confess our sins, he is faithful and just and will forgive us our sins.",
  },
  {
    number: "110",
    reference: "Revelation 22:12",
    text: "Behold, I am coming soon! My reward is with me.",
  },
  {
    number: "111",
    reference: "Matthew 6:9–10",
    text: "Our Father in heaven, hallowed be your name, your kingdom come, your will be done, on earth as it is in heaven.",
  },
  {
    number: "112",
    reference: "Matthew 6:11",
    text: "Give us today our daily bread.",
  },
  {
    number: "113",
    reference: "Matthew 6:12",
    text: "Forgive us our debts, as we also have forgiven our debtors.",
  },
  {
    number: "114",
    reference: "Matthew 6:13",
    text: "And lead us not into temptation, but deliver us from the evil one.",
  },
  {
    number: "115",
    reference: "Luke 12:32",
    text: "Do not be afraid, little flock, for your Father has been pleased to give you the kingdom.",
  },
  {
    number: "116",
    reference: "Luke 18:27",
    text: "What is impossible with man is possible with God.",
  },
  {
    number: "117",
    reference: "John 6:35",
    text: "I am the bread of life. Whoever comes to me will never go hungry.",
  },
  {
    number: "118",
    reference: "John 10:9",
    text: "I am the gate; whoever enters through me will be saved.",
  },
  {
    number: "119",
    reference: "John 14:2–3",
    text: "I go to prepare a place for you… I will come back and take you to be with me.",
  },
  {
    number: "120",
    reference: "John 14:26",
    text: "The Advocate, the Holy Spirit… will teach you all things.",
  },
  {
    number: "121",
    reference: "Acts 1:8",
    text: "You will receive power when the Holy Spirit comes on you; and you will be my witnesses.",
  },
  {
    number: "122",
    reference: "Romans 5:1",
    text: "Therefore, since we have been justified through faith, we have peace with God through our Lord Jesus Christ.",
  },
  {
    number: "123",
    reference: "Romans 8:38–39",
    text: "Nothing can separate us from the love of God that is in Christ Jesus our Lord.",
  },
  {
    number: "124",
    reference: "1 Corinthians 1:4",
    text: "I always thank my God for you because of his grace given you in Christ Jesus.",
  },
  {
    number: "125",
    reference: "2 Corinthians 1:3–4",
    text: "Praise be to the God and Father of our Lord Jesus Christ, the Father of compassion and the God of all comfort.",
  },
  {
    number: "126",
    reference: "2 Corinthians 5:17",
    text: "If anyone is in Christ, the new creation has come.",
  },
  {
    number: "127",
    reference: "Galatians 5:22–23",
    text: "The fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness, gentleness and self-control.",
  },
  {
    number: "128",
    reference: "Ephesians 2:8–9",
    text: "For it is by grace you have been saved, through faith, and this is not from yourselves, it is the gift of God.",
  },
  {
    number: "129",
    reference: "Ephesians 3:20",
    text: "Now to him who is able to do immeasurably more than all we ask or imagine, according to his power that is at work within us.",
  },
  {
    number: "130",
    reference: "Philippians 2:13",
    text: "For it is God who works in you to will and to act in order to fulfill his good purpose.",
  },
  {
    number: "131",
    reference: "Philippians 3:14",
    text: "I press on toward the goal to win the prize for which God has called me heavenward in Christ Jesus.",
  },
  {
    number: "132",
    reference: "Colossians 3:1–2",
    text: "Set your hearts on things above, not on earthly things.",
  },
  {
    number: "133",
    reference: "Colossians 3:23",
    text: "Whatever you do, work at it with all your heart, as working for the Lord, not for human masters.",
  },
  {
    number: "134",
    reference: "1 Thessalonians 5:24",
    text: "The one who calls you is faithful, and he will do it.",
  },
  {
    number: "135",
    reference: "2 Timothy 2:15",
    text: "Do your best to present yourself to God as one approved, a worker who does not need to be ashamed and correctly handles the word of truth.",
  },
  {
    number: "136",
    reference: "2 Timothy 4:7",
    text: "I have fought the good fight, I have finished the race, I have kept the faith.",
  },
  {
    number: "137",
    reference: "Titus 2:11–12",
    text: "For the grace of God has appeared, training us to say ‘No’ to ungodliness and worldly passions.",
  },
  {
    number: "138",
    reference: "Hebrews 10:24–25",
    text: "Let us consider how we may spur one another on toward love and good deeds, not giving up meeting together.",
  },
  {
    number: "139",
    reference: "Hebrews 11:6",
    text: "Without faith it is impossible to please God.",
  },
  {
    number: "140",
    reference: "James 5:16",
    text: "The prayer of a righteous person is powerful and effective.",
  },
  {
    number: "141",
    reference: "1 Peter 3:15",
    text: "But in your hearts revere Christ as Lord. Always be prepared to give an answer to everyone who asks you to give the reason for the hope that you have.",
  },
  {
    number: "142",
    reference: "1 John 4:10",
    text: "This is love: not that we loved God, but that he loved us and sent his Son as an atoning sacrifice for our sins.",
  },
  {
    number: "143",
    reference: "Revelation 3:20",
    text: "Here I am! I stand at the door and knock. If anyone hears my voice and opens the door, I will come in and eat with that person.",
  },
  {
    number: "144",
    reference: "Psalm 27:1",
    text: "The Lord is my light and my salvation, whom shall I fear?",
  },
  {
    number: "145",
    reference: "Psalm 46:1",
    text: "God is our refuge and strength, an ever-present help in trouble.",
  },
  {
    number: "146",
    reference: "Psalm 103:2–3",
    text: "Praise the Lord, my soul, and forget not all his benefits, who forgives all your sins and heals all your diseases.",
  },
  {
    number: "147",
    reference: "Isaiah 40:29",
    text: "He gives strength to the weary and increases the power of the weak.",
  },
  {
    number: "148",
    reference: "Isaiah 41:13",
    text: "For I am the Lord your God who takes hold of your right hand and says to you, ‘Do not fear; I will help you.’",
  },
  {
    number: "149",
    reference: "Isaiah 54:17",
    text: "No weapon forged against you will prevail.",
  },
  {
    number: "150",
    reference: "Jeremiah 32:17",
    text: "Ah, Sovereign Lord, you have made the heavens and the earth by your great power.",
  },
  {
    number: "151",
    reference: "Lamentations 3:22–23",
    text: "Because of the Lord’s great love we are not consumed, for his compassions never fail. They are new every morning.",
  },
  {
    number: "152",
    reference: "Ezekiel 36:26",
    text: "I will give you a new heart and put a new spirit in you.",
  },
  {
    number: "153",
    reference: "Daniel 6:22",
    text: "My God sent his angel, and he shut the mouths of the lions.",
  },
  {
    number: "154",
    reference: "Matthew 5:14–16",
    text: "You are the light of the world. Let your light shine before others.",
  },
  {
    number: "155",
    reference: "Matthew 6:33",
    text: "But seek first his kingdom and his righteousness, and all these things will be given to you as well.",
  },
  {
    number: "156",
    reference: "Matthew 11:28–30",
    text: "Come to me, all you who are weary… and you will find rest for your souls.",
  },
  {
    number: "157",
    reference: "Matthew 18:20",
    text: "For where two or three gather in my name, there am I with them.",
  },
  {
    number: "158",
    reference: "Luke 6:38",
    text: "Give, and it will be given to you. A good measure, pressed down, shaken together, and running over, will be poured into your lap.",
  },
  {
    number: "159",
    reference: "John 1:12",
    text: "Yet to all who did receive him, to those who believed in his name, he gave the right to become children of God.",
  },
  {
    number: "160",
    reference: "John 15:5",
    text: "I am the vine; you are the branches. If you remain in me, you will bear much fruit.",
  },
  {
    number: "161",
    reference: "John 15:13",
    text: "Greater love has no one than this: to lay down one’s life for one’s friends.",
  },
  {
    number: "162",
    reference: "Romans 12:1",
    text: "Offer your bodies as a living sacrifice, holy and pleasing to God, this is your true and proper worship.",
  },
  {
    number: "163",
    reference: "Romans 12:2",
    text: "Do not conform to the pattern of this world, but be transformed by the renewing of your mind.",
  },
  {
    number: "164",
    reference: "Romans 15:5–6",
    text: "May the God who gives endurance and encouragement give you the same attitude of mind toward each other that Christ Jesus had.",
  },
  {
    number: "165",
    reference: "1 Corinthians 10:13",
    text: "No temptation has overtaken you except what is common to mankind. And God is faithful; he will not let you be tempted beyond what you can bear.",
  },
  {
    number: "166",
    reference: "1 Corinthians 13:4–7",
    text: "Love is patient, love is kind… It always protects, always trusts, always hopes, always perseveres.",
  },
  {
    number: "167",
    reference: "2 Corinthians 9:6–7",
    text: "Whoever sows sparingly will also reap sparingly, and whoever sows generously will also reap generously.",
  },
  {
    number: "168",
    reference: "2 Corinthians 12:9",
    text: "My grace is sufficient for you, for my power is made perfect in weakness.",
  },
  {
    number: "169",
    reference: "Galatians 6:2",
    text: "Carry each other’s burdens, and in this way, you will fulfill the law of Christ.",
  },
  {
    number: "170",
    reference: "Ephesians 1:18–19",
    text: "I pray that the eyes of your heart may be enlightened… and that you may know the immeasurable greatness of his power for us who believe.",
  },
  {
    number: "171",
    reference: "Ephesians 3:16–17",
    text: "I pray that out of his glorious riches he may strengthen you with power through his Spirit in your inner being.",
  },
  {
    number: "172",
    reference: "Ephesians 6:10",
    text: "Finally, be strong in the Lord and in his mighty power.",
  },
  {
    number: "173",
    reference: "Ephesians 6:11",
    text: "Put on the full armor of God, so that you can take your stand against the devil’s schemes.",
  },
  {
    number: "174",
    reference: "Philippians 1:6",
    text: "Being confident of this, that he who began a good work in you will carry it on to completion until the day of Christ Jesus.",
  },
  {
    number: "175",
    reference: "Philippians 4:13",
    text: "I can do all this through him who gives me strength.",
  },
  {
    number: "176",
    reference: "Colossians 1:9–10",
    text: "We continually ask God to fill you with the knowledge of his will through all the wisdom and understanding that the Spirit gives.",
  },
  {
    number: "177",
    reference: "Colossians 3:16",
    text: "Let the message of Christ dwell among you richly as you teach and admonish one another with all wisdom.",
  },
  {
    number: "178",
    reference: "1 Thessalonians 5:11",
    text: "Therefore encourage one another and build each other up.",
  },
  {
    number: "179",
    reference: "2 Thessalonians 3:3",
    text: "But the Lord is faithful, and he will strengthen you and protect you from the evil one.",
  },
  {
    number: "180",
    reference: "1 Timothy 4:12",
    text: "Don’t let anyone look down on you because you are young, but set an example in speech, in conduct, in love, in faith and in purity.",
  },
  {
    number: "181",
    reference: "1 Timothy 6:12",
    text: "Fight the good fight of the faith. Take hold of the eternal life to which you were called.",
  },
  {
    number: "182",
    reference: "2 Timothy 1:7",
    text: "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.",
  },
  {
    number: "183",
    reference: "2 Timothy 2:1",
    text: "You then, my son, be strong in the grace that is in Christ Jesus.",
  },
  {
    number: "184",
    reference: "Titus 3:5",
    text: "He saved us, not because of righteous things we had done, but because of his mercy.",
  },
  {
    number: "185",
    reference: "Philemon 1:6",
    text: "I pray that your partnership in the faith may be effective in deepening your understanding of every good thing we share for the sake of Christ.",
  },
  {
    number: "186",
    reference: "Hebrews 12:1–2",
    text: "Let us run with perseverance the race marked out for us, fixing our eyes on Jesus.",
  },
  {
    number: "187",
    reference: "Hebrews 13:5",
    text: "Never will I leave you; never will I forsake you.",
  },
  {
    number: "188",
    reference: "James 1:12",
    text: "Blessed is the one who perseveres under trial because, having stood the test, that person will receive the crown of life.",
  },
  {
    number: "189",
    reference: "James 4:7",
    text: "Submit yourselves, then, to God. Resist the devil, and he will flee from you.",
  },
  {
    number: "190",
    reference: "1 Peter 4:10",
    text: "Each of you should use whatever gift you have received to serve others.",
  },
  {
    number: "191",
    reference: "1 Peter 5:10",
    text: "And the God of all grace, who called you to his eternal glory in Christ, after you have suffered a little while, will himself restore you and make you strong.",
  },
  {
    number: "192",
    reference: "1 John 2:15–16",
    text: "Do not love the world or anything in the world… the desires of the flesh, the lust of the eyes and the pride of life.",
  },
  {
    number: "193",
    reference: "1 John 3:18",
    text: "Dear children, let us not love with words or speech but with actions and in truth.",
  },
  {
    number: "194",
    reference: "Revelation 1:8",
    text: "I am the Alpha and the Omega, says the Lord God, who is, and who was, and who is to come, the Almighty.",
  },
  {
    number: "195",
    reference: "Revelation 21:4",
    text: "He will wipe every tear from their eyes. There will be no more death or mourning or crying or pain.",
  },
  {
    number: "196",
    reference: "Psalm 37:4",
    text: "Take delight in the Lord, and he will give you the desires of your heart.",
  },
  {
    number: "197",
    reference: "Psalm 34:8",
    text: "Taste and see that the Lord is good; blessed is the one who takes refuge in him.",
  },
  {
    number: "198",
    reference: "Psalm 119:105",
    text: "Your word is a lamp to my feet and a light for my path.",
  },
  {
    number: "199",
    reference: "Psalm 121:1–2",
    text: "I lift up my eyes to the mountains, where does my help come from? My help comes from the Lord, the Maker of heaven and earth.",
  },
  {
    number: "200",
    reference: "Psalm 145:18",
    text: "The Lord is near to all who call on him, to all who call on him in truth.",
  },
  {
    number: "201",
    reference: "Psalm 23:1",
    text: "The Lord is my shepherd, I lack nothing.",
  },
  {
    number: "202",
    reference: "Psalm 23:4",
    text: "Even though I walk through the darkest valley, I will fear no evil, for you are with me.",
  },
  {
    number: "203",
    reference: "Psalm 27:14",
    text: "Wait for the Lord; be strong and take heart and wait for the Lord.",
  },
  {
    number: "204",
    reference: "Psalm 34:17",
    text: "The righteous cry out, and the Lord hears them; he delivers them from all their troubles.",
  },
  {
    number: "205",
    reference: "Psalm 46:10",
    text: "Be still, and know that I am God.",
  },
  {
    number: "206",
    reference: "Psalm 51:10",
    text: "Create in me a pure heart, O God, and renew a steadfast spirit within me.",
  },
  {
    number: "207",
    reference: "Psalm 62:1",
    text: "Truly my soul finds rest in God; my salvation comes from him.",
  },
  {
    number: "208",
    reference: "Psalm 103:8",
    text: "The Lord is compassionate and gracious, slow to anger, abounding in love.",
  },
  {
    number: "209",
    reference: "Isaiah 26:3",
    text: "You will keep in perfect peace those whose minds are steadfast, because they trust in you.",
  },
  {
    number: "210",
    reference: "Isaiah 40:31",
    text: "But those who hope in the Lord will renew their strength.",
  },
  {
    number: "211",
    reference: "Isaiah 43:2",
    text: "When you pass through the waters, I will be with you; and through the rivers, they will not sweep over you.",
  },
  {
    number: "212",
    reference: "Jeremiah 29:11",
    text: "For I know the plans I have for you,” declares the Lord, “plans to prosper you and not to harm you.",
  },
  {
    number: "213",
    reference: "Lamentations 3:22",
    text: "Because of the Lord’s great love we are not consumed, for his compassions never fail.",
  },
  {
    number: "214",
    reference: "Micah 6:8",
    text: "He has shown you, O mortal, what is good. And what does the Lord require? To act justly, love mercy, and walk humbly.",
  },
  {
    number: "215",
    reference: "Nahum 1:7",
    text: "The Lord is good, a refuge in times of trouble. He cares for those who trust in him.",
  },
  {
    number: "216",
    reference: "Matthew 5:16",
    text: "Let your light shine before others, that they may see your good deeds and glorify your Father in heaven.",
  },
  {
    number: "217",
    reference: "Matthew 7:7",
    text: "Ask and it will be given to you; seek and you will find; knock and the door will be opened to you.",
  },
  {
    number: "218",
    reference: "Matthew 11:28",
    text: "Come to me, all you who are weary and burdened, and I will give you rest.",
  },
  {
    number: "219",
    reference: "Matthew 28:19–20",
    text: "Therefore go and make disciples of all nations, baptizing them… and teaching them to obey everything I have commanded you.",
  },
  {
    number: "220",
    reference: "Mark 10:27",
    text: "With man this is impossible, but not with God; all things are possible with God.",
  },
  {
    number: "221",
    reference: "Luke 1:37",
    text: "For no word from God will ever fail.",
  },
  {
    number: "222",
    reference: "Luke 6:36",
    text: "Be merciful, just as your Father is merciful.",
  },
  {
    number: "223",
    reference: "John 3:16",
    text: "For God so loved the world that he gave his one and only Son.",
  },
  {
    number: "224",
    reference: "John 8:12",
    text: "I am the light of the world. Whoever follows me will never walk in darkness, but will have the light of life.",
  },
  {
    number: "225",
    reference: "John 14:27",
    text: "Peace I leave with you; my peace I give you.",
  },
  {
    number: "226",
    reference: "John 16:33",
    text: "I have told you these things, so that in me you may have peace. In this world you will have trouble.",
  },
  {
    number: "227",
    reference: "Acts 2:38",
    text: "Repent and be baptized, every one of you, in the name of Jesus Christ for the forgiveness of your sins.",
  },
  {
    number: "228",
    reference: "Romans 8:28",
    text: "And we know that in all things God works for the good of those who love him.",
  },
  {
    number: "229",
    reference: "Romans 12:12",
    text: "Be joyful in hope, patient in affliction, faithful in prayer.",
  },
  {
    number: "230",
    reference: "Romans 15:13",
    text: "May the God of hope fill you with all joy and peace as you trust in him.",
  },
  {
    number: "231",
    reference: "1 Corinthians 15:57",
    text: "But thanks be to God! He gives us the victory through our Lord Jesus Christ.",
  },
  {
    number: "232",
    reference: "2 Corinthians 5:17",
    text: "Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!",
  },
  {
    number: "233",
    reference: "Galatians 5:22–23",
    text: "But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness, gentleness and self-control.",
  },
  {
    number: "234",
    reference: "Ephesians 2:8–9",
    text: "For it is by grace you have been saved, through faith, and this is not from yourselves, it is the gift of God.",
  },
  {
    number: "235",
    reference: "Philippians 2:3–4",
    text: "Do nothing out of selfish ambition or vain conceit. Rather, in humility value others above yourselves.",
  },
  {
    number: "236",
    reference: "Colossians 3:23",
    text: "Whatever you do, work at it with all your heart, as working for the Lord.",
  },
  {
    number: "237",
    reference: "1 Thessalonians 5:16–18",
    text: "Rejoice always, pray continually, give thanks in all circumstances.",
  },
  {
    number: "238",
    reference: "2 Timothy 3:16–17",
    text: "All Scripture is God-breathed and is useful for teaching, rebuking, correcting and training in righteousness.",
  },
  {
    number: "239",
    reference: "Hebrews 4:16",
    text: "Let us then approach God’s throne of grace with confidence, so that we may receive mercy and find grace to help us in our time of need.",
  },
  {
    number: "240",
    reference: "Hebrews 11:1",
    text: "Now faith is confidence in what we hope for and assurance about what we do not see.",
  },
  {
    number: "241",
    reference: "James 1:5",
    text: "If any of you lacks wisdom, you should ask God, who gives generously to all without finding fault.",
  },
  {
    number: "242",
    reference: "James 1:17",
    text: "Every good and perfect gift is from above, coming down from the Father of the heavenly lights.",
  },
  {
    number: "243",
    reference: "1 Peter 1:8–9",
    text: "Though you have not seen him, you love him; and even though you do not see him now, you believe in him.",
  },
  {
    number: "244",
    reference: "1 Peter 2:9",
    text: "But you are a chosen people, a royal priesthood, a holy nation.",
  },
  {
    number: "245",
    reference: "1 John 1:9",
    text: "If we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness.",
  },
  {
    number: "246",
    reference: "1 John 4:19",
    text: "We love because he first loved us.",
  },
  {
    number: "247",
    reference: "Revelation 3:20",
    text: "Here I am! I stand at the door and knock. If anyone hears my voice and opens the door, I will come in.",
  },
  {
    number: "248",
    reference: "Revelation 21:5",
    text: "He who was seated on the throne said, ‘I am making everything new!’",
  },
  {
    number: "249",
    reference: "Revelation 22:12",
    text: "Behold, I am coming soon! My reward is with me, and I will give to each person according to what they have done.",
  },
  {
    number: "250",
    reference: "Revelation 22:17",
    text: "The Spirit and the bride say, ‘Come!’ And let the one who hears say, ‘Come!’ Let the thirsty come; and let the one who wishes take the free gift of the water of life.",
  },
  {
    number: "251",
    reference: "Psalm 16:11",
    text: "You make known to me the path of life; you will fill me with joy in your presence.",
  },
  {
    number: "252",
    reference: "Psalm 37:5",
    text: "Commit your way to the Lord; trust in him and he will do this.",
  },
  {
    number: "253",
    reference: "Psalm 40:1–2",
    text: "I waited patiently for the Lord; he turned to me and heard my cry.",
  },
  {
    number: "254",
    reference: "Psalm 46:1–2",
    text: "God is our refuge and strength, an ever-present help in trouble.",
  },
  {
    number: "255",
    reference: "Psalm 91:2",
    text: "I will say of the Lord, ‘He is my refuge and my fortress, my God, in whom I trust.’",
  },
  {
    number: "256",
    reference: "Psalm 100:4",
    text: "Enter his gates with thanksgiving and his courts with praise; give thanks to him and praise his name.",
  },
  {
    number: "257",
    reference: "Psalm 119:11",
    text: "I have hidden your word in my heart that I might not sin against you.",
  },
  {
    number: "258",
    reference: "Psalm 121:7–8",
    text: "The Lord will keep you from all harm, he will watch over your life.",
  },
  {
    number: "259",
    reference: "Isaiah 12:2",
    text: "Surely God is my salvation; I will trust and not be afraid.",
  },
  {
    number: "260",
    reference: "Isaiah 26:4",
    text: "Trust in the Lord forever, for the Lord, the Lord himself, is the Rock eternal.",
  },
  {
    number: "261",
    reference: "Isaiah 55:8–9",
    text: "My thoughts are not your thoughts, neither are your ways my ways,” declares the Lord.",
  },
  {
    number: "262",
    reference: "Jeremiah 29:13",
    text: "You will seek me and find me when you seek me with all your heart.",
  },
  {
    number: "263",
    reference: "Lamentations 3:24",
    text: "I say to myself, ‘The Lord is my portion; therefore I will wait for him.’",
  },
  {
    number: "264",
    reference: "Daniel 3:17–18",
    text: "Our God can deliver us… But even if he does not, we will not serve your gods.",
  },
  {
    number: "265",
    reference: "Matthew 5:9",
    text: "Blessed are the peacemakers, for they will be called children of God.",
  },
  {
    number: "266",
    reference: "Matthew 6:34",
    text: "Therefore do not worry about tomorrow, for tomorrow will worry about itself.",
  },
  {
    number: "267",
    reference: "Matthew 9:37–38",
    text: "Ask the Lord of the harvest, therefore, to send out workers into his harvest field.",
  },
  {
    number: "268",
    reference: "Matthew 11:29",
    text: "Take my yoke upon you and learn from me, for I am gentle and humble in heart.",
  },
  {
    number: "269",
    reference: "Matthew 28:19",
    text: "Go and make disciples of all nations.",
  },
  {
    number: "270",
    reference: "Mark 12:30",
    text: "Love the Lord your God with all your heart and with all your soul and with all your mind and with all your strength.",
  },
  {
    number: "271",
    reference: "Luke 1:37",
    text: "For no word from God will ever fail.",
  },
  {
    number: "272",
    reference: "Luke 6:38",
    text: "Give, and it will be given to you. A good measure, pressed down, shaken together and running over, will be poured into your lap.",
  },
  {
    number: "273",
    reference: "John 10:10",
    text: "I have come that they may have life, and have it to the full.",
  },
  {
    number: "274",
    reference: "John 14:6",
    text: "I am the way and the truth and the life. No one comes to the Father except through me.",
  },
  {
    number: "275",
    reference: "John 15:12",
    text: "My command is this: Love each other as I have loved you.",
  },
  {
    number: "276",
    reference: "John 16:24",
    text: "Until now you have not asked for anything in my name. Ask and you will receive, and your joy will be complete.",
  },
  {
    number: "277",
    reference: "Acts 1:8",
    text: "But you will receive power when the Holy Spirit comes on you; and you will be my witnesses.",
  },
  {
    number: "278",
    reference: "Romans 5:8",
    text: "But God demonstrates his own love for us in this: While we were still sinners, Christ died for us.",
  },
  {
    number: "279",
    reference: "Romans 8:38–39",
    text: "Nothing can separate us from the love of God that is in Christ Jesus our Lord.",
  },
  {
    number: "280",
    reference: "Romans 12:2",
    text: "Do not conform to the pattern of this world, but be transformed by the renewing of your mind.",
  },
  {
    number: "281",
    reference: "1 Corinthians 10:13",
    text: "No temptation has overtaken you except what is common to mankind. And God is faithful; he will not let you be tempted beyond what you can bear.",
  },
  {
    number: "282",
    reference: "2 Corinthians 12:9",
    text: "My grace is sufficient for you, for my power is made perfect in weakness.",
  },
  {
    number: "283",
    reference: "Galatians 2:20",
    text: "I have been crucified with Christ and I no longer live, but Christ lives in me.",
  },
  {
    number: "284",
    reference: "Galatians 6:9",
    text: "Let us not become weary in doing good, for at the proper time we will reap a harvest.",
  },
  {
    number: "285",
    reference: "Ephesians 3:20",
    text: "Now to him who is able to do immeasurably more than all we ask or imagine, according to his power at work within us.",
  },
  {
    number: "286",
    reference: "Ephesians 4:32",
    text: "Be kind and compassionate to one another, forgiving each other, just as in Christ God forgave you.",
  },
  {
    number: "287",
    reference: "Philippians 1:9–10",
    text: "And this is my prayer: that your love may abound more and more in knowledge and depth of insight.",
  },
  {
    number: "288",
    reference: "Philippians 4:19",
    text: "And my God will meet all your needs according to the riches of his glory in Christ Jesus.",
  },
  {
    number: "289",
    reference: "Colossians 1:16–17",
    text: "For in him all things were created… all things hold together in him.",
  },
  {
    number: "290",
    reference: "Colossians 3:17",
    text: "And whatever you do, whether in word or deed, do it all in the name of the Lord Jesus.",
  },
  {
    number: "291",
    reference: "1 Thessalonians 5:18",
    text: "Give thanks in all circumstances; for this is God’s will for you in Christ Jesus.",
  },
  {
    number: "292",
    reference: "2 Thessalonians 3:16",
    text: "Now may the Lord of peace himself give you peace at all times and in every way.",
  },
  {
    number: "293",
    reference: "1 Timothy 2:1–2",
    text: "I urge, then, first of all, that petitions, prayers, intercession and thanksgiving be made for all people.",
  },
  {
    number: "294",
    reference: "2 Timothy 3:16",
    text: "All Scripture is God-breathed and is useful for teaching, rebuking, correcting and training in righteousness.",
  },
  {
    number: "295",
    reference: "Hebrews 10:24–25",
    text: "Let us consider how we may spur one another on toward love and good deeds, not giving up meeting together.",
  },
  {
    number: "296",
    reference: "Hebrews 13:8",
    text: "Jesus Christ is the same yesterday and today and forever.",
  },
  {
    number: "297",
    reference: "James 1:2–3",
    text: "Consider it pure joy, my brothers and sisters, whenever you face trials, because you know that the testing of your faith produces perseverance.",
  },
  {
    number: "298",
    reference: "James 5:16",
    text: "The prayer of a righteous person is powerful and effective.",
  },
  {
    number: "299",
    reference: "1 Peter 3:15",
    text: "Always be prepared to give an answer to everyone who asks you to give the reason for the hope that you have.",
  },
  {
    number: "300",
    reference: "1 John 4:10",
    text: "This is love: not that we loved God, but that he loved us and sent his Son as an atoning sacrifice for our sins.",
  },
  {
    number: "301",
    reference: "Revelation 1:8",
    text: "I am the Alpha and the Omega,” says the Lord God, “who is, and who was, and who is to come.",
  },
  {
    number: "302",
    reference: "Revelation 2:10",
    text: "Be faithful, even to the point of death, and I will give you life as your victor’s crown.",
  },
  {
    number: "303",
    reference: "Revelation 3:21",
    text: "To the one who is victorious, I will give the right to sit with me on my throne.",
  },
  {
    number: "304",
    reference: "Psalm 1:1–2",
    text: "Blessed is the one who does not walk in step with the wicked… but whose delight is in the law of the Lord.",
  },
  {
    number: "305",
    reference: "Psalm 19:14",
    text: "May these words of my mouth and this meditation of my heart be pleasing in your sight, Lord.",
  },
  {
    number: "306",
    reference: "Psalm 34:8",
    text: "Taste and see that the Lord is good; blessed is the one who takes refuge in him.",
  },
  {
    number: "307",
    reference: "Psalm 37:4",
    text: "Take delight in the Lord, and he will give you the desires of your heart.",
  },
  {
    number: "308",
    reference: "Psalm 103:1–2",
    text: "Praise the Lord, my soul; all my inmost being, praise his holy name.",
  },
  {
    number: "309",
    reference: "Isaiah 40:29–31",
    text: "He gives strength to the weary and increases the power of the weak. Those who hope in the Lord will renew their strength.",
  },
  {
    number: "310",
    reference: "Isaiah 41:10",
    text: "So do not fear, for I am with you; do not be dismayed, for I am your God.",
  },
  {
    number: "311",
    reference: "Jeremiah 33:3",
    text: "Call to me and I will answer you and tell you great and unsearchable things you do not know.",
  },
  {
    number: "312",
    reference: "Matthew 6:33",
    text: "But seek first his kingdom and his righteousness, and all these things will be given to you as well.",
  },
  {
    number: "313",
    reference: "Matthew 7:12",
    text: "So in everything, do to others what you would have them do to you.",
  },
  {
    number: "314",
    reference: "Matthew 19:26",
    text: "With man this is impossible, but with God all things are possible.",
  },
  {
    number: "315",
    reference: "Luke 1:37",
    text: "For nothing will be impossible with God.",
  },
  {
    number: "316",
    reference: "Luke 18:27",
    text: "Jesus replied, ‘What is impossible with man is possible with God.’",
  },
  {
    number: "317",
    reference: "John 6:35",
    text: "I am the bread of life. Whoever comes to me will never go hungry, and whoever believes in me will never be thirsty.",
  },
  {
    number: "318",
    reference: "John 15:5",
    text: "I am the vine; you are the branches. If you remain in me, you will bear much fruit.",
  },
  {
    number: "319",
    reference: "John 16:33",
    text: "In this world you will have trouble. But take heart! I have overcome the world.",
  },
  {
    number: "320",
    reference: "Romans 12:1",
    text: "Offer your bodies as a living sacrifice, holy and pleasing to God, this is your true and proper worship.",
  },
  {
    number: "321",
    reference: "Romans 15:13",
    text: "May the God of hope fill you with all joy and peace as you trust in him.",
  },
  {
    number: "322",
    reference: "1 Corinthians 13:4–7",
    text: "Love is patient, love is kind… it always protects, always trusts, always hopes, always perseveres.",
  },
  {
    number: "323",
    reference: "2 Corinthians 4:16–18",
    text: "Though outwardly we are wasting away, inwardly we are being renewed day by day.",
  },
  {
    number: "324",
    reference: "2 Corinthians 5:7",
    text: "For we live by faith, not by sight.",
  },
  {
    number: "325",
    reference: "Galatians 5:16",
    text: "So I say, walk by the Spirit, and you will not gratify the desires of the flesh.",
  },
  {
    number: "326",
    reference: "Galatians 6:2",
    text: "Carry each other’s burdens, and in this way you will fulfill the law of Christ.",
  },
  {
    number: "327",
    reference: "Ephesians 1:18–19",
    text: "I pray that the eyes of your heart may be enlightened… and that you may know the incomparably great power for us who believe.",
  },
  {
    number: "328",
    reference: "Ephesians 2:10",
    text: "For we are God’s handiwork, created in Christ Jesus to do good works.",
  },
  {
    number: "329",
    reference: "Philippians 3:14",
    text: "I press on toward the goal to win the prize for which God has called me heavenward in Christ Jesus.",
  },
  {
    number: "330",
    reference: "Philippians 4:13",
    text: "I can do all this through him who gives me strength.",
  },
  {
    number: "331",
    reference: "Colossians 3:12–14",
    text: "Clothe yourselves with compassion, kindness, humility, gentleness and patience. Bear with each other and forgive one another.",
  },
  {
    number: "332",
    reference: "Colossians 3:23",
    text: "Whatever you do, work at it with all your heart, as working for the Lord.",
  },
  {
    number: "333",
    reference: "1 Thessalonians 5:11",
    text: "Therefore encourage one another and build each other up.",
  },
  {
    number: "334",
    reference: "1 Thessalonians 5:16–18",
    text: "Rejoice always, pray continually, give thanks in all circumstances.",
  },
  {
    number: "335",
    reference: "2 Timothy 1:7",
    text: "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.",
  },
  {
    number: "336",
    reference: "2 Timothy 2:15",
    text: "Do your best to present yourself to God as one approved, a worker who does not need to be ashamed.",
  },
  {
    number: "337",
    reference: "Hebrews 12:1–2",
    text: "Let us run with perseverance the race marked out for us, fixing our eyes on Jesus.",
  },
  {
    number: "338",
    reference: "Hebrews 13:5",
    text: "Keep your lives free from the love of money and be content with what you have.",
  },
  {
    number: "339",
    reference: "James 1:5",
    text: "If any of you lacks wisdom, you should ask God, who gives generously to all without finding fault.",
  },
  {
    number: "340",
    reference: "James 1:12",
    text: "Blessed is the one who perseveres under trial because, having stood the test, that person will receive the crown of life.",
  },
  {
    number: "341",
    reference: "James 5:13",
    text: "Is anyone among you in trouble? Let them pray.",
  },
  {
    number: "342",
    reference: "1 Peter 5:7",
    text: "Cast all your anxiety on him because he cares for you.",
  },
  {
    number: "343",
    reference: "1 Peter 5:10",
    text: "And the God of all grace, who called you to his eternal glory in Christ, after you have suffered a little while, will himself restore you and make you strong.",
  },
  {
    number: "344",
    reference: "1 John 3:18",
    text: "Dear children, let us not love with words or speech but with actions and in truth.",
  },
  {
    number: "345",
    reference: "1 John 4:16",
    text: "God is love. Whoever lives in love lives in God, and God in them.",
  },
  {
    number: "346",
    reference: "Revelation 5:12",
    text: "Worthy is the Lamb, who was slain, to receive power and wealth and wisdom and strength and honor and glory and praise!",
  },
  {
    number: "347",
    reference: "Revelation 7:17",
    text: "For the Lamb at the center of the throne will be their shepherd; he will lead them to springs of living water.",
  },
  {
    number: "348",
    reference: "Revelation 21:6",
    text: "I am the Alpha and the Omega, the Beginning and the End. To the thirsty I will give water without cost from the spring of the water of life.",
  },
  {
    number: "349",
    reference: "Revelation 22:17",
    text: "The Spirit and the bride say, ‘Come!’ Let the one who hears say, ‘Come!’ Let the one who is thirsty take the water of life freely.",
  },
  {
    number: "350",
    reference: "Revelation 22:20",
    text: "He who testifies to these things says, ‘Yes, I am coming soon.’ Amen. Come, Lord Jesus.",
  },
];
