"""Generate lib/versesOfTheDay.ts from ACTS Prayers.xlsx.

Usage:
  python scripts/build-verses-of-the-day.py [path/to/ACTS Prayers.xlsx]

Default input: scripts/acts-prayers.xlsx (if present) or the Downloads path used during import.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

try:
    import openpyxl
except ImportError as exc:
    raise SystemExit('openpyxl is required: pip install openpyxl') from exc

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUTS = [
    ROOT / 'scripts' / 'acts-prayers.xlsx',
    Path(r'c:\Users\Sara\Downloads\ACTS Prayers.xlsx'),
]
OUT_PATH = ROOT / 'lib' / 'versesOfTheDay.ts'
SHEET_NAME = 'ACTS Prayer Cards'


def resolve_input_path() -> Path:
    if len(sys.argv) > 1:
        path = Path(sys.argv[1])
        if not path.exists():
            raise SystemExit(f'Input file not found: {path}')
        return path

    for candidate in DEFAULT_INPUTS:
        if candidate.exists():
            return candidate

    raise SystemExit(
        'No input workbook found. Pass a path:\n'
        '  python scripts/build-verses-of-the-day.py "path/to/ACTS Prayers.xlsx"'
    )


def ts_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def main() -> None:
    input_path = resolve_input_path()
    wb = openpyxl.load_workbook(input_path, read_only=True, data_only=True)
    if SHEET_NAME not in wb.sheetnames:
        raise SystemExit(f'Sheet not found: {SHEET_NAME!r}. Available: {wb.sheetnames}')

    ws = wb[SHEET_NAME]
    rows = list(ws.iter_rows(min_row=2, values_only=True))

    verses: list[dict[str, str]] = []
    for row in rows:
        if not row or not row[0]:
            continue

        number = str(row[0]).strip()
        reference = str(row[1] or '').strip()
        text = str(row[2] or '').strip()

        if not reference or not text:
            raise SystemExit(f'Row {number!r} is missing reference or verse text')

        verses.append(
            {
                'number': number,
                'reference': reference,
                'text': text,
            }
        )

    if not verses:
        raise SystemExit('No verses found in workbook')

    lines = [
        '// Generated by scripts/build-verses-of-the-day.py — do not edit by hand.',
        f'// Source: {input_path.name} ({len(verses)} verses)',
        '',
        'export interface DailyVerse {',
        '  number: string;',
        '  reference: string;',
        '  text: string;',
        '}',
        '',
        'export const VERSES_OF_THE_DAY: DailyVerse[] = [',
    ]

    for verse in verses:
        lines.append('  {')
        lines.append(f'    number: {ts_string(verse["number"])},')
        lines.append(f'    reference: {ts_string(verse["reference"])},')
        lines.append(f'    text: {ts_string(verse["text"])},')
        lines.append('  },')

    lines.append('];')
    lines.append('')

    OUT_PATH.write_text('\n'.join(lines), encoding='utf-8')
    print(f'Wrote {len(verses)} verses to {OUT_PATH}')


if __name__ == '__main__':
    main()
